

server:
  port: 8088

  tomcat.uri-encoding: utf-8
  servlet:
    session:
      timeout: 30m

#mybatis 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.5.36:3306/timoskins0410?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: THKJ0429@Root
    type: com.alibaba.druid.pool.DruidDataSource
  #图片上传
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  application:
    name: steam-web
    http:
      encoding:
        charset: UTF-8
        force: true
    jackson:
      default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.entity.entity
logging:
    level:
      com.example.demo.mapper: DEBUG
upload:
  url: "http://47.97.5.36:8089/upload"